name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform Deploy
    environment: main_approved
    runs-on: ubuntu-20.04
    steps:
      # Checkout el c贸digo del repositorio
      - uses: actions/checkout@v3

      # Configurar Node.js (si es necesario para el proyecto)
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      # Configuraci贸n de las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::031842254778:role/github-assume-role
          role-session-name: github-assume-session

      # Validar el c贸digo de Terraform para detectar errores de sintaxis
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      # Inicializar Terraform y generar el plan
      - name: Initialize Terraform and Plan
        run: |
          cd terraform
          terraform init -input=false
          terraform plan

      # Aplicar la configuraci贸n de Terraform (despliegue)
      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve
