name: Terraform Validate and Plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  # Job para validar la configuración de Terraform
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        shell: bash

    steps:

      # Configurar las credenciales de AWS
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::031842254778:role/github-assume-role
            role-session-name: github-assume-session

      # Checkout el código del repositorio
      - uses: actions/checkout@v3

      # Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Validar la configuración de Terraform
      - name: Terraform Validate
        run: |
          cd terraform
          terraform init -input=false || echo "Terraform init already run"
          terraform validate

      # Mostrar el plan
      - name: Terraform Plan
        run: terraform plan
